### ISSUE TITLE
Problemas con la práctica 2.

### ISSUE THREAD

**Issue by FranciscoNaveros** [romilgildo/IV-PLUCO-RMH#1]
En configuración correcta de herramientas de contrucción se refiere a que hagas un makefile (o cualquier otra opción que te parezca) para realizar todas las tareas con una sola orden. Por ejemplo, para pasar los test en local, que sea simplemente hacer make test y que esto llame a mocha test/test.js, python test.py o lo que sea que uses para pasar los test.

Este makefile irá aumentando con cada práctica.

**Comment by romilgildo** [comment]
De acuerdo, gracias, ahora lo arreglo.

**Comment by romilgildo** [comment]
Ya lo he añadido, creo que así está bien
